### ISSUE TITLE
Multiple snyk vulnerabilities in this project.

### ISSUE THREAD

**Issue by rusiarohit** [camunda/camunda-bpm-sdk-js#30]
Hi Team,

I use this as node module in my application and while trying to cleanup the vulnerabilities I found various vulnerabilities are due to this module in my dependency.

`✗ High severity vulnerability found on uglify-js@2.2.5
- desc: Improper minification of non-boolean comparisons
- info: https://snyk.io/vuln/npm:uglify-js:20150824
- from: test@1.544.0 > camunda-bpm-sdk-js@7.7.3 > grunt-browserify@2.1.0 > watchify@0.6.4 > browserify@3.46.1 > umd@2.0.0 > ruglify@1.0.0 > uglify-js@2.2.5`

`✗ High severity vulnerability found on qs@2.3.3
- desc: Prototype Override Protection Bypass
- info: https://snyk.io/vuln/npm:qs:20170213
- from: compliagov@1.544.0 > camunda-bpm-sdk-js@7.7.3 > superagent@1.4.0 > qs@2.3.3`

`✗ High severity vulnerability found on minimatch@0.2.14
- desc: Regular Expression Denial of Service (DoS)
- info: https://snyk.io/vuln/npm:minimatch:20160620
- from: compliagov@1.544.0 > camunda-bpm-sdk-js@7.7.3 > grunt@0.4.5 > glob@3.1.21 > minimatch@0.2.14`

`✗ High severity vulnerability found on angular@1.2.29
- desc: Arbitrary Code Execution
- info: https://snyk.io/vuln/npm:angular:20150310
- from: compliagov@1.544.0 > camunda-bpm-sdk-js@7.7.3 > angular@1.2.29
Upgrade direct dependency angular@1.2.29 to angular@1.5.0`

`✗ Medium severity vulnerability found on concat-stream@1.4.10
- desc: Uninitialized Memory Exposure
- info: https://snyk.io/vuln/npm:concat-stream:20160901
- from: compliagov@1.544.0 > camunda-bpm-sdk-js@7.7.3 > grunt-browserify@2.1.0 > watchify@0.6.4 > browserify@3.46.1 > insert-module-globals@6.0.0 > concat-stream@1.4.10
Upgrade direct dependency browserify@3.46.1 to browserify@12.0.0 (triggers upgrades to module-deps@4.0.2 > concat-stream@1.5.2)`

I guess most of these dependency of this project, which are causing vulnerabilities, are for the development purpose and so can we move them to devDependency to make sure they don't  affect the production?

**Comment by romansmirnov** [comment]
Hi @rusiarohit,

Thanks for raising this issue.

We already noticed that some of the used dependencies have vulnerabilities, see [1]. As a next step we are going to investigate which impact an upgrade of the dependencies would have, and of course we are going to fix the vulnerabilities.

We will let you know once fixed it.

Best,
Roman

[1]: https://app.camunda.com/jira/browse/CAM-8473

**Comment by rusiarohit** [comment]
Thanks for the update @romansmirnov. Would you be able to share the approx. fix date? If it's beyond our go-live date I might have to look for forking and update myself. 

Cheers,
RR

**Comment by romansmirnov** [comment]
@rusiarohit,

We take the vulnerabilities serious and of course we will fix them asap, but I cannot predict a fix date right now.

When is your go-live date?

Best,
Roman

**Comment by rusiarohit** [comment]
@romansmirnov It's February 15th 2018. Will appreciate it if we can turn this around before that. Earlier I had tried to contribute in this project and was not able to commit. I had some other features/improvements in other services within this project as well. We use it extensively in our project.

-RR

**Comment by romansmirnov** [comment]
@rusiarohit ,

We had a look into the used dependencies.

The vulnerabilities 

* High severity vulnerability found on uglify-js@2.2.5
* Medium severity vulnerability found on concat-stream@1.4.10

are caused by the used dependency `grunt-browserify@2.1.0`, and the vulnerability

* High severity vulnerability found on minimatch@0.2.14

is caused by the used dependency `grunt@0.4.5`.

Due to our build infrastructure and pipeline we cannot declare these dependencies (i.e. `grunt-browserify` and `grunt`) as dev devDependencies. But these dependencies are __not__ part of the distribution and they __don't__ affect the production.

The vulnerability

* High severity vulnerability found on qs@2.3.3

is caused by the used dependency `superagent@1.4.0`.

Here we are going to investigate as a next step, what would be the impact of upgrading this dependency to a recent one, because according to [1] there are some breaking changes.

Regarding the optional dependency `angular@1.2.29` I have the followng questions:
* How do you actually use the `camunda-bpm-sdk-js` package?
* Do you use the angular forms SDK? If not, you could use the argument `--no-optional` when executing `npm install`, then angular should not be part of package.

Best,
Roman

[1]: https://github.com/visionmedia/superagent/blob/master/History.md

**Comment by rusiarohit** [comment]
Hey Roman,

Sorry, I was out of work for sometime.

Regarding `grunt-browserify@2.1.0` & `grunt@0.4.5`, What you mean by *these dependencies are not part of the distribution and they don't affect the production*. They are getting installed as npm module in when we build our project.

Please keep me posted `superagent@1.4.0` on this one.

Regarding `angular@1.2.29`, We use the camunda-bpm-sdk-js package as npm module not to be used by our angular module directly. We have node wrapper/service layer which uses the camunda-bpm-sdk-js module internally as we have lot of our business logic to apply on top of it.

`--no-optional` works fine in my local but we can't define that in `package.json` and during build each time it does install optional dependency.
